import React from 'react';

function Terms() {
  return (
    <div className="pt-40 min-h-screen bg-gradient-to-br from-gray-900 via-gray-800 to-gray-900 text-white px-4 sm:px-6 lg:px-8">
      <div className="max-w-4xl mx-auto">
        <h1 className="text-4xl font-bold mb-12 text-center bg-clip-text text-transparent bg-gradient-to-r from-blue-400 to-purple-500">
          Terms & Conditions
        </h1>

        <div className="bg-white/5 backdrop-blur-lg border border-white/10 rounded-2xl shadow-xl p-8 space-y-6">
          <div className="prose prose-invert max-w-none">
            <p className="text-gray-300">
              This document is an electronic record in terms of Information Technology Act, 2000 and rules there under as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.
            </p>

            <p className="text-gray-300">
              This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy and Terms of Use for access or usage of Suraj Electronics ("Website"), including the related mobile site and mobile application (hereinafter referred to as "Platform").
            </p>

            <h2 className="text-2xl font-semibold text-blue-400 mt-8 mb-4">1. Platform Ownership</h2>
            <p className="text-gray-300">
              The Platform is owned by Suraj Electronics, a company incorporated under the Companies Act, 1956 with its registered office at [Your Address] (hereinafter referred to as "Platform Owner", "we", "us", "our").
            </p>

            <h2 className="text-2xl font-semibold text-blue-400 mt-8 mb-4">2. Acceptance of Terms</h2>
            <p className="text-gray-300">
              Your use of the Platform and services and tools are governed by the following terms and conditions ("Terms of Use") as applicable to the Platform including the applicable policies which are incorporated herein by way of reference. If You transact on the Platform, You shall be subject to the policies that are applicable to the Platform for such transaction.
            </p>

            <h2 className="text-2xl font-semibold text-blue-400 mt-8 mb-4">3. User Obligations</h2>
            <ul className="list-disc list-inside text-gray-300 space-y-2">
              <li>You agree to provide true, accurate and complete information during registration</li>
              <li>You shall be responsible for all acts done through the use of your registered account</li>
              <li>You agree not to use the Platform for any unlawful or illegal purposes</li>
              <li>You agree to pay all charges associated with availing the Services</li>
            </ul>

            <h2 className="text-2xl font-semibold text-blue-400 mt-8 mb-4">4. Intellectual Property</h2>
            <p className="text-gray-300">
              The contents of the Platform and the Services are proprietary to us and are licensed to us. You will not have any authority to claim any intellectual property rights, title, or interest in its contents. The contents includes and is not limited to the design, layout, look and graphics.
            </p>

            <h2 className="text-2xl font-semibold text-blue-400 mt-8 mb-4">5. Limitation of Liability</h2>
            <p className="text-gray-300">
              In no event will the Platform Owner be liable for any indirect, consequential, incidental, special or punitive damages, including without limitation damages for loss of profits or revenues, business interruption, loss of business opportunities, loss of data or loss of other economic interests, whether in contract, negligence, tort or otherwise, arising from the use of or inability to use the Services.
            </p>

            <h2 className="text-2xl font-semibold text-blue-400 mt-8 mb-4">6. Governing Law</h2>
            <p className="text-gray-300">
              These Terms and any dispute or claim relating to it, or its enforceability, shall be governed by and construed in accordance with the laws of India. All disputes arising out of or in connection with these Terms shall be subject to the exclusive jurisdiction of the courts in [Your City and State].
            </p>

            <h2 className="text-2xl font-semibold text-blue-400 mt-8 mb-4">7. Contact Information</h2>
            <p className="text-gray-300">
              All concerns or communications relating to these Terms must be communicated to us using the contact information provided on this website.
            </p>

            <div className="mt-12 pt-6 border-t border-white/10">
              <p className="text-gray-400 text-sm">
                Last updated: {new Date().toLocaleDateString()}
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

export default Terms; 